CREATE TABLE LOJAS (
	CODIGO		INT			NOT NULL,
	NOME		VARCHAR(50) NOT NULL,
	IND_INATIVO	INT			NOT NULL DEFAULT 0
	CONSTRAINT LOJAS_PK PRIMARY KEY (CODIGO)
)
;



INSERT INTO LOJAS(CODIGO, NOME) VALUES (1000, 'Filial São Caetano do Sul');
INSERT INTO LOJAS(CODIGO, NOME) VALUES (2000, 'Filial Santo André');
INSERT INTO LOJAS(CODIGO, NOME) VALUES (3000, 'Filial São Bernardo do Campo');

SELECT * FROM LOJAS

CREATE TABLE ESTOQUE(
	CODIGO_PRODUTO INT NOT NULL,
	CODIGO_FILIAL  INT NOT NULL,
	QUANTIDADE	   DECIMAL NOT NULL DEFAULT 0,
	CONSTRAINT ESTOQUE_PK PRIMARY KEY(CODIGO_PRODUTO, CODIGO_FILIAL)

); 

INSERT INTO ESTOQUE(CODIGO_PRODUTO, CODIGO_FILIAL, QUANTIDADE) VALUES (99, 10, 1)

SELECT * FROM ESTOQUE

DELETE FROM ESTOQUE

ALTER TABLE ESTOQUE
ADD CONSTRAINT FK_ESTOQUE_PRODUTO 
	FOREIGN KEY (CODIGO_PRODUTO)
	REFERENCES  PRODUTOS(CODIGO);
	 

ALTER TABLE ESTOQUE
ADD CONSTRAINT FK_ESTOQUE_LOJAS
	FOREIGN KEY (CODIGO_FILIAL)
	REFERENCES  LOJAS(CODIGO);



INSERT INTO ESTOQUE(CODIGO_PRODUTO, CODIGO_FILIAL, QUANTIDADE) VALUES (1, 1000, 1)

ALTER TABLE ESTOQUE
DROP CONSTRAINT FK_ESTOQUE_LOJAS
	

SELECT E.CODIGO_FILIAL,
	   L.NOME,
	   E.CODIGO_PRODUTO,
	   P.DESCRICAO,
	   E.QUANTIDADE
	FROM ESTOQUE E INNER JOIN LOJAS L
	  ON E.CODIGO_FILIAL = L.CODIGO
	 INNER JOIN PRODUTOS P
	   ON E.CODIGO_PRODUTO = P.CODIGO
